main :
	g++ -o main.exe main.cpp BinarySearchTree.cpp BinaryNode.cpp NodeQueue.cpp

analyze:
	g++ -o analyze.exe analyze.cpp BinarySearchTree.cpp BinaryNode.cpp NodeQueue.cpp

clean:
	rm -f *.exe
	rm -f main
	rm -f analyze
	rm -f BinaryNode
	rm -f BinarySearchTree
